### ISSUE TITLE
Уровень скрипта

### ISSUE THREAD

**Issue by demist** [jullak/testBashScript#1]
Добрый день!

1. В репозитории есть лишние файлы - их нужно удалить
2. Скрипт сильно сложнее того, что мы проходили. 
Вы уже до этого были знакомы с bash?

**Comment by jullak** [comment]
Лишние файлы удалены
Нет, с bash до этого знакома не была, просто было интересно попробовать сделать проверку на обновление, не делая каждый раз коммит всех файлов.

**Comment by demist** [comment]
Понятно.
Теперь ок.
